// Auto-generated component registry. Generated by scripts/generate-live-controls.mjs
// Do not edit manually — re-run the script.

export interface ComponentControl {
  name: string;
  type: 'text' | 'number' | 'boolean' | 'select';
  options?: string[];
}

export interface ComponentConfig {
  name: string;
  layer: 'atoms' | 'composites' | 'templates';
  file: string;
  description: string;
  defaultProps: Record<string, unknown>;
  propControls: ComponentControl[];
}

export const componentRegistry: ComponentConfig[] = [
  {
    "name": "Avatar",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/Avatar.tsx",
    "description": "Avatar component (atoms)",
    "defaultProps": {
      "name": "",
      "initials": "",
      "src": "",
      "size": "sm"
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "initials",
        "type": "text"
      },
      {
        "name": "src",
        "type": "text"
      },
      {
        "name": "size",
        "type": "select",
        "options": [
          "sm",
          "md",
          "lg",
          "xl"
        ]
      }
    ]
  },
  {
    "name": "CitationRef",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/CitationRef.tsx",
    "description": "CitationRef component (atoms)",
    "defaultProps": {
      "author": "",
      "year": 0,
      "locator": "",
      "href": "",
      "variant": "inline"
    },
    "propControls": [
      {
        "name": "author",
        "type": "text"
      },
      {
        "name": "year",
        "type": "number"
      },
      {
        "name": "locator",
        "type": "text"
      },
      {
        "name": "href",
        "type": "text"
      },
      {
        "name": "variant",
        "type": "select",
        "options": [
          "inline",
          "footnote",
          "parenthetical"
        ]
      }
    ]
  },
  {
    "name": "ClaimMarker",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/ClaimMarker.tsx",
    "description": "ClaimMarker component (atoms)",
    "defaultProps": {
      "index": 0,
      "confidence": 0,
      "href": ""
    },
    "propControls": [
      {
        "name": "index",
        "type": "number"
      },
      {
        "name": "confidence",
        "type": "number"
      },
      {
        "name": "href",
        "type": "text"
      }
    ]
  },
  {
    "name": "ConceptTerm",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/ConceptTerm.tsx",
    "description": "ConceptTerm component (atoms)",
    "defaultProps": {
      "term": "",
      "type": "noun",
      "definition": "",
      "href": ""
    },
    "propControls": [
      {
        "name": "term",
        "type": "text"
      },
      {
        "name": "type",
        "type": "select",
        "options": [
          "noun",
          "verb",
          "adjective",
          "phrase",
          "abbreviation"
        ]
      },
      {
        "name": "definition",
        "type": "text"
      },
      {
        "name": "href",
        "type": "text"
      }
    ]
  },
  {
    "name": "ConfidenceBar",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/ConfidenceBar.tsx",
    "description": "ConfidenceBar component (atoms)",
    "defaultProps": {
      "value": 0,
      "max": 0,
      "variant": "low",
      "showValue": false
    },
    "propControls": [
      {
        "name": "value",
        "type": "number"
      },
      {
        "name": "max",
        "type": "number"
      },
      {
        "name": "variant",
        "type": "select",
        "options": [
          "low",
          "medium",
          "high",
          "stated"
        ]
      },
      {
        "name": "showValue",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "DOILink",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/DOILink.tsx",
    "description": "DOILink component (atoms)",
    "defaultProps": {
      "doi": "",
      "short": false
    },
    "propControls": [
      {
        "name": "doi",
        "type": "text"
      },
      {
        "name": "short",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "EvidenceStrength",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/EvidenceStrength.tsx",
    "description": "EvidenceStrength component (atoms)",
    "defaultProps": {
      "tier": "anecdotal",
      "showLabel": false
    },
    "propControls": [
      {
        "name": "tier",
        "type": "select",
        "options": [
          "anecdotal",
          "weak",
          "moderate",
          "strong",
          "conclusive"
        ]
      },
      {
        "name": "showLabel",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "HashDigest",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/HashDigest.tsx",
    "description": "HashDigest component (atoms)",
    "defaultProps": {
      "hash": "",
      "algorithm": "sha256",
      "prefix": false
    },
    "propControls": [
      {
        "name": "hash",
        "type": "text"
      },
      {
        "name": "algorithm",
        "type": "select",
        "options": [
          "sha256",
          "sha1",
          "md5",
          "blake3"
        ]
      },
      {
        "name": "prefix",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "Icon",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/Icon.tsx",
    "description": "Icon component (atoms)",
    "defaultProps": {
      "name": "",
      "size": "xs",
      "color": ""
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "size",
        "type": "select",
        "options": [
          "xs",
          "sm",
          "md",
          "lg",
          "xl"
        ]
      },
      {
        "name": "color",
        "type": "text"
      }
    ]
  },
  {
    "name": "LanguageTag",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/LanguageTag.tsx",
    "description": "LanguageTag component (atoms)",
    "defaultProps": {
      "language": "",
      "variant": "plain"
    },
    "propControls": [
      {
        "name": "language",
        "type": "text"
      },
      {
        "name": "variant",
        "type": "select",
        "options": [
          "plain",
          "compact",
          "minimal"
        ]
      }
    ]
  },
  {
    "name": "LicenseIcon",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/LicenseIcon.tsx",
    "description": "LicenseIcon component (atoms)",
    "defaultProps": {
      "license": "CC-BY",
      "href": ""
    },
    "propControls": [
      {
        "name": "license",
        "type": "text"
      },
      {
        "name": "href",
        "type": "text"
      }
    ]
  },
  {
    "name": "PathBreadcrumb",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/PathBreadcrumb.tsx",
    "description": "PathBreadcrumb component (atoms)",
    "defaultProps": {
      "segment": "",
      "href": "",
      "icon": "folder"
    },
    "propControls": [
      {
        "name": "segment",
        "type": "text"
      },
      {
        "name": "href",
        "type": "text"
      },
      {
        "name": "icon",
        "type": "select",
        "options": [
          "folder",
          "file",
          "package"
        ]
      }
    ]
  },
  {
    "name": "ProvenanceMarker",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/ProvenanceMarker.tsx",
    "description": "ProvenanceMarker component (atoms)",
    "defaultProps": {
      "kind": "primary",
      "source": ""
    },
    "propControls": [
      {
        "name": "kind",
        "type": "select",
        "options": [
          "primary",
          "derived",
          "cited",
          "verified",
          "inferred",
          "speculative"
        ]
      },
      {
        "name": "source",
        "type": "text"
      }
    ]
  },
  {
    "name": "RelationVerb",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/RelationVerb.tsx",
    "description": "RelationVerb component (atoms)",
    "defaultProps": {
      "verb": "is-a",
      "direction": "forward"
    },
    "propControls": [
      {
        "name": "verb",
        "type": "text"
      },
      {
        "name": "direction",
        "type": "select",
        "options": [
          "forward",
          "backward",
          "bidirectional"
        ]
      }
    ]
  },
  {
    "name": "ReviewerChip",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/ReviewerChip.tsx",
    "description": "ReviewerChip component (atoms)",
    "defaultProps": {
      "name": "",
      "initials": "",
      "role": "",
      "decision": "approved"
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "initials",
        "type": "text"
      },
      {
        "name": "role",
        "type": "text"
      },
      {
        "name": "decision",
        "type": "select",
        "options": [
          "approved",
          "rejected",
          "pending",
          "abstained"
        ]
      }
    ]
  },
  {
    "name": "SeverityDot",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/SeverityDot.tsx",
    "description": "SeverityDot component (atoms)",
    "defaultProps": {
      "severity": "info",
      "label": "",
      "size": "sm",
      "pulsing": false
    },
    "propControls": [
      {
        "name": "severity",
        "type": "select",
        "options": [
          "info",
          "success",
          "caution",
          "warning",
          "error",
          "critical"
        ]
      },
      {
        "name": "label",
        "type": "text"
      },
      {
        "name": "size",
        "type": "select",
        "options": [
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "pulsing",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "StatusPill",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/StatusPill.tsx",
    "description": "StatusPill component (atoms)",
    "defaultProps": {
      "status": "open",
      "label": "",
      "size": "sm"
    },
    "propControls": [
      {
        "name": "status",
        "type": "text"
      },
      {
        "name": "label",
        "type": "text"
      },
      {
        "name": "size",
        "type": "select",
        "options": [
          "sm",
          "md"
        ]
      }
    ]
  },
  {
    "name": "TimestampAtom",
    "layer": "atoms",
    "file": "ports/react/knowledge/atoms/TimestampAtom.tsx",
    "description": "TimestampAtom component (atoms)",
    "defaultProps": {
      "iso": "",
      "relative": "",
      "variant": "absolute"
    },
    "propControls": [
      {
        "name": "iso",
        "type": "text"
      },
      {
        "name": "relative",
        "type": "text"
      },
      {
        "name": "variant",
        "type": "select",
        "options": [
          "absolute",
          "relative",
          "both"
        ]
      }
    ]
  },
  {
    "name": "ADRCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ADRCard.tsx",
    "description": "ADRCard component (composites)",
    "defaultProps": {
      "number": "",
      "title": "",
      "status": "proposed",
      "date": "",
      "context": "",
      "decision": "",
      "consequences": []
    },
    "propControls": [
      {
        "name": "number",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "status",
        "type": "select",
        "options": [
          "proposed",
          "accepted",
          "rejected",
          "superseded",
          "deprecated"
        ]
      },
      {
        "name": "date",
        "type": "text"
      },
      {
        "name": "context",
        "type": "text"
      },
      {
        "name": "decision",
        "type": "text"
      },
      {
        "name": "consequences",
        "type": "text"
      }
    ]
  },
  {
    "name": "APIReference",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/APIReference.tsx",
    "description": "APIReference component (composites)",
    "defaultProps": {
      "endpoint": null,
      "class": ""
    },
    "propControls": [
      {
        "name": "endpoint",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "Alert",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Alert.tsx",
    "description": "Alert component (composites)",
    "defaultProps": {
      "variant": "info",
      "title": "",
      "dismissible": false
    },
    "propControls": [
      {
        "name": "variant",
        "type": "select",
        "options": [
          "info",
          "success",
          "caution",
          "warning",
          "error",
          "danger"
        ]
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "dismissible",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "ArchitectureDiagram",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ArchitectureDiagram.tsx",
    "description": "ArchitectureDiagram component (composites)",
    "defaultProps": {
      "nodes": [],
      "edges": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "nodes",
        "type": "text"
      },
      {
        "name": "edges",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "AuditTrail",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/AuditTrail.tsx",
    "description": "AuditTrail component (composites)",
    "defaultProps": {
      "events": [],
      "filterable": false
    },
    "propControls": [
      {
        "name": "events",
        "type": "text"
      },
      {
        "name": "filterable",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "Breadcrumb",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Breadcrumb.tsx",
    "description": "Breadcrumb component (composites)",
    "defaultProps": {
      "items": []
    },
    "propControls": [
      {
        "name": "items",
        "type": "text"
      }
    ]
  },
  {
    "name": "Button",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Button.tsx",
    "description": "Button component (composites)",
    "defaultProps": {
      "variant": "primary",
      "size": "sm",
      "disabled": false,
      "loading": false,
      "href": "",
      "type": "button",
      "ariaLabel": "",
      "onClick": null
    },
    "propControls": [
      {
        "name": "variant",
        "type": "select",
        "options": [
          "primary",
          "secondary",
          "ghost",
          "danger"
        ]
      },
      {
        "name": "size",
        "type": "select",
        "options": [
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "disabled",
        "type": "boolean"
      },
      {
        "name": "loading",
        "type": "boolean"
      },
      {
        "name": "href",
        "type": "text"
      },
      {
        "name": "type",
        "type": "select",
        "options": [
          "button",
          "submit",
          "reset"
        ]
      },
      {
        "name": "ariaLabel",
        "type": "text"
      },
      {
        "name": "onClick",
        "type": "text"
      }
    ]
  },
  {
    "name": "Card",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Card.tsx",
    "description": "Card component (composites)",
    "defaultProps": {
      "interactive": false
    },
    "propControls": [
      {
        "name": "interactive",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "ChartBar",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ChartBar.tsx",
    "description": "ChartBar component (composites)",
    "defaultProps": {
      "data": [],
      "height": 0,
      "showAxis": false,
      "showValues": false,
      "class": ""
    },
    "propControls": [
      {
        "name": "data",
        "type": "text"
      },
      {
        "name": "height",
        "type": "number"
      },
      {
        "name": "showAxis",
        "type": "boolean"
      },
      {
        "name": "showValues",
        "type": "boolean"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "CitationChain",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/CitationChain.tsx",
    "description": "CitationChain component (composites)",
    "defaultProps": {
      "citations": [],
      "label": "",
      "separator": "arrow"
    },
    "propControls": [
      {
        "name": "citations",
        "type": "text"
      },
      {
        "name": "label",
        "type": "text"
      },
      {
        "name": "separator",
        "type": "select",
        "options": [
          "arrow",
          "pipe",
          "dot"
        ]
      }
    ]
  },
  {
    "name": "CodeBlock",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/CodeBlock.tsx",
    "description": "CodeBlock component (composites)",
    "defaultProps": {
      "code": "",
      "language": "python",
      "filename": "",
      "highlightLines": 0,
      "showLineNumbers": false,
      "theme": "github-dark",
      "class": ""
    },
    "propControls": [
      {
        "name": "code",
        "type": "text"
      },
      {
        "name": "language",
        "type": "text"
      },
      {
        "name": "filename",
        "type": "text"
      },
      {
        "name": "highlightLines",
        "type": "number"
      },
      {
        "name": "showLineNumbers",
        "type": "boolean"
      },
      {
        "name": "theme",
        "type": "select",
        "options": [
          "github-dark",
          "github-light"
        ]
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "ComplianceStatus",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ComplianceStatus.tsx",
    "description": "ComplianceStatus component (composites)",
    "defaultProps": {
      "framework": "",
      "controls": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "framework",
        "type": "text"
      },
      {
        "name": "controls",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "ConceptCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ConceptCard.tsx",
    "description": "ConceptCard component (composites)",
    "defaultProps": {
      "term": "",
      "definition": "",
      "type": "",
      "relations": [],
      "source": ""
    },
    "propControls": [
      {
        "name": "term",
        "type": "text"
      },
      {
        "name": "definition",
        "type": "text"
      },
      {
        "name": "type",
        "type": "text"
      },
      {
        "name": "relations",
        "type": "text"
      },
      {
        "name": "source",
        "type": "text"
      }
    ]
  },
  {
    "name": "DatasetSpec",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/DatasetSpec.tsx",
    "description": "DatasetSpec component (composites)",
    "defaultProps": {
      "name": "",
      "version": "",
      "size": "",
      "format": "",
      "license": "",
      "schema": [],
      "ethicalNotes": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "version",
        "type": "text"
      },
      {
        "name": "size",
        "type": "text"
      },
      {
        "name": "format",
        "type": "text"
      },
      {
        "name": "license",
        "type": "text"
      },
      {
        "name": "schema",
        "type": "text"
      },
      {
        "name": "ethicalNotes",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "DeploymentStatus",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/DeploymentStatus.tsx",
    "description": "DeploymentStatus component (composites)",
    "defaultProps": {
      "environments": []
    },
    "propControls": [
      {
        "name": "environments",
        "type": "text"
      }
    ]
  },
  {
    "name": "DialogueTree",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/DialogueTree.tsx",
    "description": "DialogueTree component (composites)",
    "defaultProps": {
      "nodes": [],
      "rootId": ""
    },
    "propControls": [
      {
        "name": "nodes",
        "type": "text"
      },
      {
        "name": "rootId",
        "type": "text"
      }
    ]
  },
  {
    "name": "EmptyState",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/EmptyState.tsx",
    "description": "EmptyState component (composites)",
    "defaultProps": {
      "icon": "",
      "title": "",
      "description": "",
      "actionLabel": "",
      "actionHref": ""
    },
    "propControls": [
      {
        "name": "icon",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "description",
        "type": "text"
      },
      {
        "name": "actionLabel",
        "type": "text"
      },
      {
        "name": "actionHref",
        "type": "text"
      }
    ]
  },
  {
    "name": "EvidenceReceipt",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/EvidenceReceipt.tsx",
    "description": "EvidenceReceipt component (composites)",
    "defaultProps": {
      "id": "",
      "type": "document",
      "description": "",
      "hash": "",
      "hashAlgorithm": "sha256",
      "timestamp": "",
      "witness": "",
      "locator": ""
    },
    "propControls": [
      {
        "name": "id",
        "type": "text"
      },
      {
        "name": "type",
        "type": "select",
        "options": [
          "document",
          "testimony",
          "observation",
          "measurement",
          "artifact"
        ]
      },
      {
        "name": "description",
        "type": "text"
      },
      {
        "name": "hash",
        "type": "text"
      },
      {
        "name": "hashAlgorithm",
        "type": "select",
        "options": [
          "sha256",
          "sha1",
          "blake3"
        ]
      },
      {
        "name": "timestamp",
        "type": "text"
      },
      {
        "name": "witness",
        "type": "text"
      },
      {
        "name": "locator",
        "type": "text"
      }
    ]
  },
  {
    "name": "ExperimentCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ExperimentCard.tsx",
    "description": "ExperimentCard component (composites)",
    "defaultProps": {
      "id": "",
      "title": "",
      "hypothesis": "",
      "method": "",
      "results": "",
      "conclusion": "",
      "outcome": "confirmed",
      "class": ""
    },
    "propControls": [
      {
        "name": "id",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "hypothesis",
        "type": "text"
      },
      {
        "name": "method",
        "type": "text"
      },
      {
        "name": "results",
        "type": "text"
      },
      {
        "name": "conclusion",
        "type": "text"
      },
      {
        "name": "outcome",
        "type": "select",
        "options": [
          "confirmed",
          "refuted",
          "inconclusive",
          "in-progress"
        ]
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "FeatureCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/FeatureCard.tsx",
    "description": "FeatureCard component (composites)",
    "defaultProps": {
      "icon": "",
      "title": "",
      "description": "",
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "icon",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "description",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "FormField",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/FormField.tsx",
    "description": "FormField component (composites)",
    "defaultProps": {
      "label": "",
      "htmlFor": "",
      "required": false,
      "optional": false,
      "helper": ""
    },
    "propControls": [
      {
        "name": "label",
        "type": "text"
      },
      {
        "name": "htmlFor",
        "type": "text"
      },
      {
        "name": "required",
        "type": "boolean"
      },
      {
        "name": "optional",
        "type": "boolean"
      },
      {
        "name": "helper",
        "type": "text"
      }
    ]
  },
  {
    "name": "GlossaryIndex",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/GlossaryIndex.tsx",
    "description": "GlossaryIndex component (composites)",
    "defaultProps": {
      "entries": [],
      "filterable": false
    },
    "propControls": [
      {
        "name": "entries",
        "type": "text"
      },
      {
        "name": "filterable",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "HumanGate",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/HumanGate.tsx",
    "description": "HumanGate component (composites)",
    "defaultProps": {
      "id": "",
      "name": "",
      "description": "",
      "reviewer": "",
      "reviewerRole": "",
      "decision": "approved",
      "sealedAt": "",
      "criteria": []
    },
    "propControls": [
      {
        "name": "id",
        "type": "text"
      },
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "description",
        "type": "text"
      },
      {
        "name": "reviewer",
        "type": "text"
      },
      {
        "name": "reviewerRole",
        "type": "text"
      },
      {
        "name": "decision",
        "type": "select",
        "options": [
          "approved",
          "rejected",
          "pending",
          "escalated"
        ]
      },
      {
        "name": "sealedAt",
        "type": "text"
      },
      {
        "name": "criteria",
        "type": "text"
      }
    ]
  },
  {
    "name": "LinkGroup",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/LinkGroup.tsx",
    "description": "LinkGroup component (composites)",
    "defaultProps": {
      "title": "",
      "links": [],
      "variant": "horizontal"
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "links",
        "type": "text"
      },
      {
        "name": "variant",
        "type": "select",
        "options": [
          "horizontal",
          "vertical"
        ]
      }
    ]
  },
  {
    "name": "List",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/List.tsx",
    "description": "List component (composites)",
    "defaultProps": {
      "items": [],
      "variant": "normal"
    },
    "propControls": [
      {
        "name": "items",
        "type": "text"
      },
      {
        "name": "variant",
        "type": "select",
        "options": [
          "normal",
          "compact"
        ]
      }
    ]
  },
  {
    "name": "ListGrid",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ListGrid.tsx",
    "description": "ListGrid component (composites)",
    "defaultProps": {
      "items": [],
      "columns": 0
    },
    "propControls": [
      {
        "name": "items",
        "type": "text"
      },
      {
        "name": "columns",
        "type": "number"
      }
    ]
  },
  {
    "name": "ModelCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ModelCard.tsx",
    "description": "ModelCard component (composites)",
    "defaultProps": {
      "name": "",
      "version": "",
      "purpose": "",
      "trainingData": "",
      "evalResults": [],
      "knownLimits": [],
      "intendedUse": "",
      "outOfScope": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "version",
        "type": "text"
      },
      {
        "name": "purpose",
        "type": "text"
      },
      {
        "name": "trainingData",
        "type": "text"
      },
      {
        "name": "evalResults",
        "type": "text"
      },
      {
        "name": "knownLimits",
        "type": "text"
      },
      {
        "name": "intendedUse",
        "type": "text"
      },
      {
        "name": "outOfScope",
        "type": "text"
      }
    ]
  },
  {
    "name": "NarrativeArc",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/NarrativeArc.tsx",
    "description": "NarrativeArc component (composites)",
    "defaultProps": {
      "beats": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "beats",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "OntologyRelation",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/OntologyRelation.tsx",
    "description": "OntologyRelation component (composites)",
    "defaultProps": {
      "subject": "",
      "subjectType": "",
      "verb": null,
      "object": "",
      "objectType": "",
      "direction": "forward"
    },
    "propControls": [
      {
        "name": "subject",
        "type": "text"
      },
      {
        "name": "subjectType",
        "type": "text"
      },
      {
        "name": "verb",
        "type": "text"
      },
      {
        "name": "object",
        "type": "text"
      },
      {
        "name": "objectType",
        "type": "text"
      },
      {
        "name": "direction",
        "type": "select",
        "options": [
          "forward",
          "backward",
          "bidirectional"
        ]
      }
    ]
  },
  {
    "name": "Pagination",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Pagination.tsx",
    "description": "Pagination component (composites)",
    "defaultProps": {
      "currentPage": 0,
      "totalPages": 0,
      "onPageChange": 0
    },
    "propControls": [
      {
        "name": "currentPage",
        "type": "number"
      },
      {
        "name": "totalPages",
        "type": "number"
      },
      {
        "name": "onPageChange",
        "type": "number"
      }
    ]
  },
  {
    "name": "PaperSummary",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/PaperSummary.tsx",
    "description": "PaperSummary component (composites)",
    "defaultProps": {
      "title": "",
      "authors": [],
      "year": 0,
      "venue": "",
      "abstract": "",
      "claims": [],
      "limitations": [],
      "citationCount": 0,
      "doi": "",
      "class": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "authors",
        "type": "text"
      },
      {
        "name": "year",
        "type": "number"
      },
      {
        "name": "venue",
        "type": "text"
      },
      {
        "name": "abstract",
        "type": "text"
      },
      {
        "name": "claims",
        "type": "text"
      },
      {
        "name": "limitations",
        "type": "text"
      },
      {
        "name": "citationCount",
        "type": "number"
      }
    ]
  },
  {
    "name": "PolicyCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/PolicyCard.tsx",
    "description": "PolicyCard component (composites)",
    "defaultProps": {
      "id": "",
      "title": "",
      "statement": "",
      "effectiveDate": "",
      "scope": "",
      "owner": "",
      "status": null
    },
    "propControls": [
      {
        "name": "id",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "statement",
        "type": "text"
      },
      {
        "name": "effectiveDate",
        "type": "text"
      },
      {
        "name": "scope",
        "type": "text"
      },
      {
        "name": "owner",
        "type": "text"
      },
      {
        "name": "status",
        "type": "text"
      }
    ]
  },
  {
    "name": "PricingCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/PricingCard.tsx",
    "description": "PricingCard component (composites)",
    "defaultProps": {
      "tier": "",
      "price": "",
      "period": "",
      "features": [],
      "ctaLabel": "",
      "ctaHref": "",
      "highlighted": false
    },
    "propControls": [
      {
        "name": "tier",
        "type": "text"
      },
      {
        "name": "price",
        "type": "text"
      },
      {
        "name": "period",
        "type": "text"
      },
      {
        "name": "features",
        "type": "text"
      },
      {
        "name": "ctaLabel",
        "type": "text"
      },
      {
        "name": "ctaHref",
        "type": "text"
      },
      {
        "name": "highlighted",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "ProductCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ProductCard.tsx",
    "description": "ProductCard component (composites)",
    "defaultProps": {
      "title": "",
      "description": "",
      "price": "",
      "href": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "description",
        "type": "text"
      },
      {
        "name": "price",
        "type": "text"
      },
      {
        "name": "href",
        "type": "text"
      }
    ]
  },
  {
    "name": "ProfileCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ProfileCard.tsx",
    "description": "ProfileCard component (composites)",
    "defaultProps": {
      "name": "",
      "title": "",
      "bio": "",
      "avatarSrc": ""
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "bio",
        "type": "text"
      },
      {
        "name": "avatarSrc",
        "type": "text"
      }
    ]
  },
  {
    "name": "Progress",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Progress.tsx",
    "description": "Progress component (composites)",
    "defaultProps": {
      "value": 0,
      "label": "",
      "variant": "ember"
    },
    "propControls": [
      {
        "name": "value",
        "type": "number"
      },
      {
        "name": "label",
        "type": "text"
      },
      {
        "name": "variant",
        "type": "select",
        "options": [
          "ember",
          "signal",
          "success",
          "caution"
        ]
      }
    ]
  },
  {
    "name": "ProjectStatus",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/ProjectStatus.tsx",
    "description": "ProjectStatus component (composites)",
    "defaultProps": {
      "name": "",
      "owner": "",
      "status": null,
      "progress": 0,
      "lastActivity": "",
      "blockers": [],
      "nextMilestone": ""
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "owner",
        "type": "text"
      },
      {
        "name": "status",
        "type": "text"
      },
      {
        "name": "progress",
        "type": "number"
      },
      {
        "name": "lastActivity",
        "type": "text"
      },
      {
        "name": "blockers",
        "type": "text"
      },
      {
        "name": "nextMilestone",
        "type": "text"
      }
    ]
  },
  {
    "name": "PromptPattern",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/PromptPattern.tsx",
    "description": "PromptPattern component (composites)",
    "defaultProps": {
      "name": "",
      "category": "reasoning",
      "template": "",
      "variables": [],
      "example": "",
      "author": "",
      "class": ""
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "category",
        "type": "select",
        "options": [
          "reasoning",
          "extraction",
          "transformation",
          "generation",
          "analysis",
          "tooling"
        ]
      },
      {
        "name": "template",
        "type": "text"
      },
      {
        "name": "variables",
        "type": "text"
      },
      {
        "name": "example",
        "type": "text"
      },
      {
        "name": "author",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "QuoteCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/QuoteCard.tsx",
    "description": "QuoteCard component (composites)",
    "defaultProps": {
      "quote": "",
      "attribution": "",
      "source": "",
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "quote",
        "type": "text"
      },
      {
        "name": "attribution",
        "type": "text"
      },
      {
        "name": "source",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "RunLog",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/RunLog.tsx",
    "description": "RunLog component (composites)",
    "defaultProps": {
      "entries": [],
      "filterable": false
    },
    "propControls": [
      {
        "name": "entries",
        "type": "text"
      },
      {
        "name": "filterable",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "SchemaViewer",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/SchemaViewer.tsx",
    "description": "SchemaViewer component (composites)",
    "defaultProps": {
      "name": "",
      "fields": [],
      "description": "",
      "class": ""
    },
    "propControls": [
      {
        "name": "name",
        "type": "text"
      },
      {
        "name": "fields",
        "type": "text"
      },
      {
        "name": "description",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "SearchBar",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/SearchBar.tsx",
    "description": "SearchBar component (composites)",
    "defaultProps": {
      "placeholder": "",
      "onSubmit": ""
    },
    "propControls": [
      {
        "name": "placeholder",
        "type": "text"
      },
      {
        "name": "onSubmit",
        "type": "text"
      }
    ]
  },
  {
    "name": "Select",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Select.tsx",
    "description": "Select component (composites)",
    "defaultProps": {
      "options": [],
      "value": "",
      "placeholder": "",
      "onChange": ""
    },
    "propControls": [
      {
        "name": "options",
        "type": "text"
      },
      {
        "name": "value",
        "type": "text"
      },
      {
        "name": "placeholder",
        "type": "text"
      },
      {
        "name": "onChange",
        "type": "text"
      }
    ]
  },
  {
    "name": "SequenceDiagram",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/SequenceDiagram.tsx",
    "description": "SequenceDiagram component (composites)",
    "defaultProps": {
      "actors": [],
      "messages": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "actors",
        "type": "text"
      },
      {
        "name": "messages",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "SourceChain",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/SourceChain.tsx",
    "description": "SourceChain component (composites)",
    "defaultProps": {
      "root": null
    },
    "propControls": [
      {
        "name": "root",
        "type": "text"
      }
    ]
  },
  {
    "name": "StatCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/StatCard.tsx",
    "description": "StatCard component (composites)",
    "defaultProps": {
      "value": 0,
      "label": "",
      "trend": null,
      "context": "",
      "accent": "success"
    },
    "propControls": [
      {
        "name": "value",
        "type": "number"
      },
      {
        "name": "label",
        "type": "text"
      },
      {
        "name": "trend",
        "type": "text"
      },
      {
        "name": "context",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "success",
          "caution",
          "error",
          "balanced",
          "ember",
          "signal",
          "violet",
          "gold"
        ]
      }
    ]
  },
  {
    "name": "StateMachine",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/StateMachine.tsx",
    "description": "StateMachine component (composites)",
    "defaultProps": {
      "states": [],
      "transitions": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "states",
        "type": "text"
      },
      {
        "name": "transitions",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "Stepper",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Stepper.tsx",
    "description": "Stepper component (composites)",
    "defaultProps": {
      "steps": [],
      "currentStep": 0
    },
    "propControls": [
      {
        "name": "steps",
        "type": "text"
      },
      {
        "name": "currentStep",
        "type": "number"
      }
    ]
  },
  {
    "name": "SynthesisSummary",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/SynthesisSummary.tsx",
    "description": "SynthesisSummary component (composites)",
    "defaultProps": {
      "title": "",
      "claims": [],
      "consensus": 0
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "claims",
        "type": "text"
      },
      {
        "name": "consensus",
        "type": "number"
      }
    ]
  },
  {
    "name": "Tabs",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Tabs.tsx",
    "description": "Tabs component (composites)",
    "defaultProps": {
      "tabs": []
    },
    "propControls": [
      {
        "name": "tabs",
        "type": "text"
      }
    ]
  },
  {
    "name": "TaskHierarchy",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/TaskHierarchy.tsx",
    "description": "TaskHierarchy component (composites)",
    "defaultProps": {
      "tasks": [],
      "initiallyExpanded": false
    },
    "propControls": [
      {
        "name": "tasks",
        "type": "text"
      },
      {
        "name": "initiallyExpanded",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "TaxonomyTree",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/TaxonomyTree.tsx",
    "description": "TaxonomyTree component (composites)",
    "defaultProps": {
      "root": null,
      "initiallyExpanded": 0
    },
    "propControls": [
      {
        "name": "root",
        "type": "text"
      },
      {
        "name": "initiallyExpanded",
        "type": "number"
      }
    ]
  },
  {
    "name": "TestimonialCard",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/TestimonialCard.tsx",
    "description": "TestimonialCard component (composites)",
    "defaultProps": {
      "quote": "",
      "author": "",
      "role": "",
      "rating": 0,
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "quote",
        "type": "text"
      },
      {
        "name": "author",
        "type": "text"
      },
      {
        "name": "role",
        "type": "text"
      },
      {
        "name": "rating",
        "type": "number"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "Textarea",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Textarea.tsx",
    "description": "Textarea component (composites)",
    "defaultProps": {
      "placeholder": "",
      "rows": 0,
      "value": "",
      "onChange": ""
    },
    "propControls": [
      {
        "name": "placeholder",
        "type": "text"
      },
      {
        "name": "rows",
        "type": "number"
      },
      {
        "name": "value",
        "type": "text"
      },
      {
        "name": "onChange",
        "type": "text"
      }
    ]
  },
  {
    "name": "Toast",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/Toast.tsx",
    "description": "Toast component (composites)",
    "defaultProps": {
      "visible": false,
      "variant": null,
      "title": "",
      "position": "top-right",
      "duration": 0
    },
    "propControls": [
      {
        "name": "visible",
        "type": "boolean"
      },
      {
        "name": "variant",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "position",
        "type": "select",
        "options": [
          "top-right",
          "top-left",
          "bottom-right",
          "bottom-left"
        ]
      },
      {
        "name": "duration",
        "type": "number"
      }
    ]
  },
  {
    "name": "VersionDiff",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/VersionDiff.tsx",
    "description": "VersionDiff component (composites)",
    "defaultProps": {
      "before": [],
      "after": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "before",
        "type": "text"
      },
      {
        "name": "after",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "WorkflowState",
    "layer": "composites",
    "file": "ports/react/knowledge/composites/WorkflowState.tsx",
    "description": "WorkflowState component (composites)",
    "defaultProps": {
      "states": [],
      "current": "",
      "transitions": []
    },
    "propControls": [
      {
        "name": "states",
        "type": "text"
      },
      {
        "name": "current",
        "type": "text"
      },
      {
        "name": "transitions",
        "type": "text"
      }
    ]
  },
  {
    "name": "ADRIndex",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/ADRIndex.tsx",
    "description": "ADRIndex component (templates)",
    "defaultProps": {
      "adrs": [],
      "filterable": false,
      "class": ""
    },
    "propControls": [
      {
        "name": "adrs",
        "type": "text"
      },
      {
        "name": "filterable",
        "type": "boolean"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "APIDocumentationPage",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/APIDocumentationPage.tsx",
    "description": "APIDocumentationPage component (templates)",
    "defaultProps": {
      "apiName": "",
      "version": "",
      "baseUrl": "",
      "sections": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "apiName",
        "type": "text"
      },
      {
        "name": "version",
        "type": "text"
      },
      {
        "name": "baseUrl",
        "type": "text"
      },
      {
        "name": "sections",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "AuditReport",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/AuditReport.tsx",
    "description": "AuditReport component (templates)",
    "defaultProps": {
      "title": "",
      "scope": "",
      "auditor": "",
      "auditedEntity": "",
      "period": "",
      "findings": [],
      "auditTrail": [],
      "compliance": [],
      "status": "pass",
      "class": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "scope",
        "type": "text"
      },
      {
        "name": "auditor",
        "type": "text"
      },
      {
        "name": "auditedEntity",
        "type": "text"
      },
      {
        "name": "period",
        "type": "text"
      },
      {
        "name": "findings",
        "type": "text"
      },
      {
        "name": "auditTrail",
        "type": "text"
      },
      {
        "name": "compliance",
        "type": "text"
      }
    ]
  },
  {
    "name": "CodePlayground",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/CodePlayground.tsx",
    "description": "CodePlayground component (templates)",
    "defaultProps": {
      "title": "",
      "code": "",
      "language": "python",
      "output": "",
      "explanation": "",
      "class": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "code",
        "type": "text"
      },
      {
        "name": "language",
        "type": "text"
      },
      {
        "name": "output",
        "type": "text"
      },
      {
        "name": "explanation",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "ComplianceDashboard",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/ComplianceDashboard.tsx",
    "description": "ComplianceDashboard component (templates)",
    "defaultProps": {
      "frameworks": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "frameworks",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "ComponentPlayground",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/ComponentPlayground.tsx",
    "description": "ComponentPlayground component (templates)",
    "defaultProps": {
      "componentName": "",
      "initialProps": [],
      "propMeta": [],
      "previewHtml": "",
      "class": ""
    },
    "propControls": [
      {
        "name": "componentName",
        "type": "text"
      },
      {
        "name": "initialProps",
        "type": "text"
      },
      {
        "name": "propMeta",
        "type": "text"
      },
      {
        "name": "previewHtml",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "CreativeProjectBrief",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/CreativeProjectBrief.tsx",
    "description": "CreativeProjectBrief component (templates)",
    "defaultProps": {
      "title": "",
      "premise": "",
      "arc": [],
      "sampleDialogue": [],
      "characters": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "premise",
        "type": "text"
      },
      {
        "name": "arc",
        "type": "text"
      },
      {
        "name": "sampleDialogue",
        "type": "text"
      },
      {
        "name": "characters",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "Dashboard",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/Dashboard.tsx",
    "description": "Dashboard component (templates)",
    "defaultProps": {
      "navItems": [],
      "title": ""
    },
    "propControls": [
      {
        "name": "navItems",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      }
    ]
  },
  {
    "name": "DecisionWorkspace",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/DecisionWorkspace.tsx",
    "description": "DecisionWorkspace component (templates)",
    "defaultProps": {
      "initialADR": 0,
      "class": ""
    },
    "propControls": [
      {
        "name": "initialADR",
        "type": "number"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "EvidencePackage",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/EvidencePackage.tsx",
    "description": "EvidencePackage component (templates)",
    "defaultProps": {
      "title": "",
      "claim": "",
      "receipts": [],
      "sealedBy": "",
      "sealedAt": "",
      "class": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "claim",
        "type": "text"
      },
      {
        "name": "receipts",
        "type": "text"
      },
      {
        "name": "sealedBy",
        "type": "text"
      },
      {
        "name": "sealedAt",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "ExperimentNotebook",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/ExperimentNotebook.tsx",
    "description": "ExperimentNotebook component (templates)",
    "defaultProps": {
      "title": "",
      "experiments": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "experiments",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "HeaderLayout",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/HeaderLayout.tsx",
    "description": "HeaderLayout component (templates)",
    "defaultProps": {
      "title": "",
      "stickyHeader": false
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "stickyHeader",
        "type": "boolean"
      }
    ]
  },
  {
    "name": "HeroCentered",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/HeroCentered.tsx",
    "description": "HeroCentered component (templates)",
    "defaultProps": {
      "eyebrow": "",
      "title": "",
      "lede": "",
      "accent": "hearth",
      "size": "sm"
    },
    "propControls": [
      {
        "name": "eyebrow",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "lede",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      },
      {
        "name": "size",
        "type": "select",
        "options": [
          "sm",
          "md",
          "lg"
        ]
      }
    ]
  },
  {
    "name": "HeroSplit",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/HeroSplit.tsx",
    "description": "HeroSplit component (templates)",
    "defaultProps": {
      "eyebrow": "",
      "title": "",
      "lede": "",
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "eyebrow",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "lede",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "KnowledgeBaseBrowser",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/KnowledgeBaseBrowser.tsx",
    "description": "KnowledgeBaseBrowser component (templates)",
    "defaultProps": {
      "taxonomy": false,
      "sections": [],
      "searchable": false,
      "class": ""
    },
    "propControls": [
      {
        "name": "taxonomy",
        "type": "boolean"
      },
      {
        "name": "sections",
        "type": "text"
      },
      {
        "name": "searchable",
        "type": "boolean"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "KnowledgeGraphView",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/KnowledgeGraphView.tsx",
    "description": "KnowledgeGraphView component (templates)",
    "defaultProps": {
      "nodes": [],
      "edges": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "nodes",
        "type": "text"
      },
      {
        "name": "edges",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "LayoutGrid",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/LayoutGrid.tsx",
    "description": "LayoutGrid component (templates)",
    "defaultProps": {
      "columns": 0,
      "gap": "sm"
    },
    "propControls": [
      {
        "name": "columns",
        "type": "number"
      },
      {
        "name": "gap",
        "type": "select",
        "options": [
          "sm",
          "normal",
          "lg"
        ]
      }
    ]
  },
  {
    "name": "LayoutSidebar",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/LayoutSidebar.tsx",
    "description": "LayoutSidebar component (templates)",
    "defaultProps": {
      "sidebarPosition": "left",
      "sidebarWidth": ""
    },
    "propControls": [
      {
        "name": "sidebarPosition",
        "type": "select",
        "options": [
          "left",
          "right"
        ]
      },
      {
        "name": "sidebarWidth",
        "type": "text"
      }
    ]
  },
  {
    "name": "LayoutStack",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/LayoutStack.tsx",
    "description": "LayoutStack component (templates)",
    "defaultProps": {
      "gap": "sm",
      "align": "start"
    },
    "propControls": [
      {
        "name": "gap",
        "type": "select",
        "options": [
          "sm",
          "normal",
          "lg"
        ]
      },
      {
        "name": "align",
        "type": "select",
        "options": [
          "start",
          "center",
          "end",
          "stretch"
        ]
      }
    ]
  },
  {
    "name": "Modal",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/Modal.tsx",
    "description": "Modal component (templates)",
    "defaultProps": {
      "id": "",
      "title": "",
      "size": "sm"
    },
    "propControls": [
      {
        "name": "id",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "size",
        "type": "select",
        "options": [
          "sm",
          "md",
          "lg"
        ]
      }
    ]
  },
  {
    "name": "OperationsRunbook",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/OperationsRunbook.tsx",
    "description": "OperationsRunbook component (templates)",
    "defaultProps": {
      "title": "",
      "procedure": [],
      "recentLogs": [],
      "oncall": "",
      "class": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "procedure",
        "type": "text"
      },
      {
        "name": "recentLogs",
        "type": "text"
      },
      {
        "name": "oncall",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "PageFooter",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/PageFooter.tsx",
    "description": "PageFooter component (templates)",
    "defaultProps": {
      "copyright": "",
      "columns": []
    },
    "propControls": [
      {
        "name": "copyright",
        "type": "text"
      },
      {
        "name": "columns",
        "type": "text"
      }
    ]
  },
  {
    "name": "PageHeader",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/PageHeader.tsx",
    "description": "PageHeader component (templates)",
    "defaultProps": {
      "title": "",
      "subtitle": "",
      "size": "sm",
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "subtitle",
        "type": "text"
      },
      {
        "name": "size",
        "type": "select",
        "options": [
          "sm",
          "md",
          "lg"
        ]
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "PolicyDocument",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/PolicyDocument.tsx",
    "description": "PolicyDocument component (templates)",
    "defaultProps": {
      "id": "",
      "title": "",
      "effectiveDate": "",
      "reviewDate": "",
      "owner": "",
      "sections": [],
      "gates": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "id",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "effectiveDate",
        "type": "text"
      },
      {
        "name": "reviewDate",
        "type": "text"
      },
      {
        "name": "owner",
        "type": "text"
      },
      {
        "name": "sections",
        "type": "text"
      },
      {
        "name": "gates",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "ReleaseNotes",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/ReleaseNotes.tsx",
    "description": "ReleaseNotes component (templates)",
    "defaultProps": {
      "product": "",
      "releases": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "product",
        "type": "text"
      },
      {
        "name": "releases",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "ResearchBrief",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/ResearchBrief.tsx",
    "description": "ResearchBrief component (templates)",
    "defaultProps": {
      "paper": null,
      "related": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "paper",
        "type": "text"
      },
      {
        "name": "related",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "SectionCTA",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/SectionCTA.tsx",
    "description": "SectionCTA component (templates)",
    "defaultProps": {
      "title": "",
      "description": "",
      "primaryCtaLabel": "",
      "primaryCtaHref": "",
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "description",
        "type": "text"
      },
      {
        "name": "primaryCtaLabel",
        "type": "text"
      },
      {
        "name": "primaryCtaHref",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "SectionContent",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/SectionContent.tsx",
    "description": "SectionContent component (templates)",
    "defaultProps": {
      "eyebrow": "",
      "title": "",
      "lede": "",
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "eyebrow",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "lede",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "SectionFeatures",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/SectionFeatures.tsx",
    "description": "SectionFeatures component (templates)",
    "defaultProps": {
      "eyebrow": "",
      "title": "",
      "lede": "",
      "features": [],
      "columns": 0,
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "eyebrow",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "lede",
        "type": "text"
      },
      {
        "name": "features",
        "type": "text"
      },
      {
        "name": "columns",
        "type": "number"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "SectionPricing",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/SectionPricing.tsx",
    "description": "SectionPricing component (templates)",
    "defaultProps": {
      "eyebrow": "",
      "title": "",
      "tiers": [],
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "eyebrow",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "tiers",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "SectionTestimonials",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/SectionTestimonials.tsx",
    "description": "SectionTestimonials component (templates)",
    "defaultProps": {
      "eyebrow": "",
      "title": "",
      "testimonials": [],
      "accent": "hearth"
    },
    "propControls": [
      {
        "name": "eyebrow",
        "type": "text"
      },
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "testimonials",
        "type": "text"
      },
      {
        "name": "accent",
        "type": "select",
        "options": [
          "hearth",
          "code",
          "balanced",
          "ember",
          "signal",
          "violet"
        ]
      }
    ]
  },
  {
    "name": "StepperLayout",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/StepperLayout.tsx",
    "description": "StepperLayout component (templates)",
    "defaultProps": {
      "steps": [],
      "currentStep": 0
    },
    "propControls": [
      {
        "name": "steps",
        "type": "text"
      },
      {
        "name": "currentStep",
        "type": "number"
      }
    ]
  },
  {
    "name": "SystemArchitectureDoc",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/SystemArchitectureDoc.tsx",
    "description": "SystemArchitectureDoc component (templates)",
    "defaultProps": {
      "title": "",
      "version": "",
      "sections": [],
      "class": ""
    },
    "propControls": [
      {
        "name": "title",
        "type": "text"
      },
      {
        "name": "version",
        "type": "text"
      },
      {
        "name": "sections",
        "type": "text"
      },
      {
        "name": "class",
        "type": "text"
      }
    ]
  },
  {
    "name": "TabsLayout",
    "layer": "templates",
    "file": "ports/react/knowledge/templates/TabsLayout.tsx",
    "description": "TabsLayout component (templates)",
    "defaultProps": {
      "tabs": []
    },
    "propControls": [
      {
        "name": "tabs",
        "type": "text"
      }
    ]
  }
];

export const componentsByLayer = {
  atoms: componentRegistry.filter(c => c.layer === 'atoms'),
  composites: componentRegistry.filter(c => c.layer === 'composites'),
  templates: componentRegistry.filter(c => c.layer === 'templates'),
};
